# coding: utf-8

"""
    Most Popular

    Provides services for getting the most popular articles on NYTimes.com based on emails, shares, or views.  Get most emailed articles for the last day: ``` /emailed/1.json ```  Get most shared articles on Facebook for the last day: ``` /shared/1/facebook.json ```  Get most viewed articles for the last seven days: ``` /viewed/7.json ```  ## Example Calls ``` https://api.nytimes.com/svc/mostpopular/v2/emailed/7.json?api-key=yourkey ```  ``` https://api.nytimes.com/svc/mostpopular/v2/shared/1/facebook.json?api-key=yourkey ```  ``` https://api.nytimes.com/svc/mostpopular/v2/viewed/1.json?api-key=yourkey ``` 

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

import sys
from setuptools import setup, find_packages

NAME = "swagger_client"
VERSION = "1.0.0"

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Most Popular",
    author_email="",
    url="",
    keywords=["Swagger", "Most Popular"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    Provides services for getting the most popular articles on NYTimes.com based on emails, shares, or views.  Get most emailed articles for the last day: &#x60;&#x60;&#x60; /emailed/1.json &#x60;&#x60;&#x60;  Get most shared articles on Facebook for the last day: &#x60;&#x60;&#x60; /shared/1/facebook.json &#x60;&#x60;&#x60;  Get most viewed articles for the last seven days: &#x60;&#x60;&#x60; /viewed/7.json &#x60;&#x60;&#x60;  ## Example Calls &#x60;&#x60;&#x60; https://api.nytimes.com/svc/mostpopular/v2/emailed/7.json?api-key&#x3D;yourkey &#x60;&#x60;&#x60;  &#x60;&#x60;&#x60; https://api.nytimes.com/svc/mostpopular/v2/shared/1/facebook.json?api-key&#x3D;yourkey &#x60;&#x60;&#x60;  &#x60;&#x60;&#x60; https://api.nytimes.com/svc/mostpopular/v2/viewed/1.json?api-key&#x3D;yourkey &#x60;&#x60;&#x60; 
    """
)
